# Generated by Django 4.1 on 2024-07-10 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_alter_manufacturer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='registration',
            new_name='drivers',
        ),
    ]
