# Generated by Django 4.1 on 2025-08-29 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0002_alter_car_drivers"),
        ("taxi", "0003_alter_manufacturer_name"),
    ]

    operations = []
