# Generated by Django 5.0.7 on 2024-07-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='hobby',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
